// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdnw2BXAvS5ibLRMrJ-tdM8pJAdw7iIOM',
    appId: '1:885646030804:web:940afd78040e184ba7c841',
    messagingSenderId: '885646030804',
    projectId: 'srd104d1app-b73a9',
    authDomain: 'srd104d1app-b73a9.firebaseapp.com',
    storageBucket: 'srd104d1app-b73a9.firebasestorage.app',
    measurementId: 'G-W5FQJTWFVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1zsBHU4RkH44rNEkpPuE8-aBmE45679k',
    appId: '1:885646030804:android:dbdbabeea4f0fac0a7c841',
    messagingSenderId: '885646030804',
    projectId: 'srd104d1app-b73a9',
    storageBucket: 'srd104d1app-b73a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyyYTsGSjdXf1YUp24nlvM6glP-sIg9cE',
    appId: '1:885646030804:ios:1602e89d17480027a7c841',
    messagingSenderId: '885646030804',
    projectId: 'srd104d1app-b73a9',
    storageBucket: 'srd104d1app-b73a9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyyYTsGSjdXf1YUp24nlvM6glP-sIg9cE',
    appId: '1:885646030804:ios:1602e89d17480027a7c841',
    messagingSenderId: '885646030804',
    projectId: 'srd104d1app-b73a9',
    storageBucket: 'srd104d1app-b73a9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdnw2BXAvS5ibLRMrJ-tdM8pJAdw7iIOM',
    appId: '1:885646030804:web:772a820127720dd3a7c841',
    messagingSenderId: '885646030804',
    projectId: 'srd104d1app-b73a9',
    authDomain: 'srd104d1app-b73a9.firebaseapp.com',
    storageBucket: 'srd104d1app-b73a9.firebasestorage.app',
    measurementId: 'G-832YYF4GCJ',
  );
}
