import 'package:bbusrd104/models/category_model.dart';
import 'package:bbusrd104/services/category_service.dart';
import 'package:get/get.dart';

class CategoryController extends GetxController {
  // Add your controller logic here
  
  // fields 
  final CategoryService service ; 

  final isLoading = false.obs; // Observable to track loading state

  // constructor
  CategoryController(this.service);

  // add category
  Future<bool> addCategory({required String categoryName, String? description}) 
  async {
    try {
      isLoading.value = true; // Set loading state to true before operation
      final category = CategoryModel(
        id: '', // ID will be generated by Firestore
        categoryName: categoryName,
        description: description,
      );
      await service.addCategory(category);
      return true;
    } catch (ex) {
      Get.snackbar('Error', 'Failed to add category: ${ex.toString()}',
      snackPosition: SnackPosition.BOTTOM,
      duration: Duration(seconds: 5)
      );
      return false; // Return false to indicate failure
    } finally {
      isLoading.value = false; // Set loading state to false after operation 
    }
    
  }

  // get categories
  
}